[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environments]
  [environments.production]
    envVars = [
      { key = "NODE_ENV", value = "production" },
      { key = "API_KEY", value = "${{ secrets.API_KEY }}" },
      { key = "DATABASE_URL", value = "file:/data/sqlite.db" },
      { key = "NEXT_PUBLIC_URL", value = "https://www.a-pl.xyz" }
    ]
    plugins = [
      { name = "sqlite", value = "latest" }
    ]
    persistentStorage = [
      { path = "/data", size = "1Gi" }
    ] 